### ISSUE TITLE
Excess cpu usage

### ISSUE THREAD

**Issue by jds11235** [poiuedws/awesomedotfiles#1]
sorry for communicating with you again, but I felt like I should follow through on my promise to look this over. I believe the issue is this updates the module, and below it is re-updated when these changes occur, causing a possible loop consuming extra cpu resources. See the timer below and the update_all_content function
```
-- Update time progress every 5 seconds
local update_music_info = gears.timer {
	timeout = 1.0,
	autostart = true,
	call_now = true,
	callback  = function()

		-- Update progress bar
		update_progress_bar()

		-- Update time progress
		update_time_progress()

		-- Update time duration
		update_time_duration()

		-- Update title
		update_title()


    -- Check if playing or paused
    check_if_playing()

    -- Check repeat status
    check_repeat_status()

    -- Check random status
    check_random_status()


	collectgarbage('collect')

end
}


mpd_updater.music_play_pause = music_play_pause
mpd_updater.music_next = music_next
mpd_updater.music_prev = music_prev
mpd_updater.music_rep = music_rep
mpd_updater.music_rand = music_rand
mpd_updater.update_all_content = update_all_content

return mpd_updater
```

**Comment by jds11235** [comment]
nvm just got further into the code, this is not the case

**Comment by jds11235** [comment]
can you look at the exact threads which are using a lot of CPU using `top -H`? It is possible this is just bash being pokey

**Comment by koaie** [comment]
![image](https://user-images.githubusercontent.com/13078659/71598043-48a51800-2b3d-11ea-93b6-7a36fc44b91a.png)

**Comment by koaie** [comment]
![image](https://user-images.githubusercontent.com/13078659/71598079-66727d00-2b3d-11ea-80fc-b555dea5fcc9.png)

**Comment by jds11235** [comment]
`top -H` doesn't work for you? might be caps sensitive

**Comment by jds11235** [comment]
unblock me on discord so we can discuss

**Comment by koaie** [comment]
![image](https://user-images.githubusercontent.com/13078659/71598170-b7827100-2b3d-11ea-976f-2587d14479d0.png)
